server:
    host: 0.0.0.0 
    port: 8080
llm:
    base_url: https://token-plan-cn.xiaomimimo.com/v1
    api_key: tp-csyan88gqwgzs6pmfdbvhbzfxo1l1xcw0wnxikp401e6gaor
    model: mimo-v2.5-pro
    max_completion_tokens: 8192
embedding:
    base_url: https://ai.gitee.com/v1
    api_key: YUF4KWW6VYUSBC3VH5YIMPMJUFMU1H6NKEMRGX1N
    model: Qwen3-Embedding-8B
prometheus:
    url: http://localhost:9090
chromadb:
    url: http://chromadb:8088